version: "3.9"
services:
  mai_streaming:
    build:
      context: src/mai_streaming
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - /home/mpaul/projects/tw/tw-dns/ddos_data:/ddos_data
    environment:
      - ES_URL=${ES_URL:-http://elasticsearch:9200}
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_SAVED_OBJECTS_BULK_CREATE=true
    volumes:
      - ./kibana/dashboards:/usr/share/kibana/dashboards
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
  kibana_data:
